// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD90rU5ecYSXirDL4cLbYBQx_L8xaNZ7ww',
    appId: '1:118878690268:android:be3092e3b0e78d841f0d19',
    messagingSenderId: '118878690268',
    projectId: 'nextcommerce-01',
    databaseURL: 'https://nextcommerce-01-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nextcommerce-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdlDtY85CdOIFUR8epchP2CH_0Usa-pxU',
    appId: '1:118878690268:ios:57a01594567ef0011f0d19',
    messagingSenderId: '118878690268',
    projectId: 'nextcommerce-01',
    databaseURL: 'https://nextcommerce-01-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nextcommerce-01.firebasestorage.app',
    iosBundleId: 'com.example.algeriaBeautyWebview',
  );
}
